#!/bin/sh -x

# Clear database
#for i in `/usr/local/pgsql/bin/psql -U store_user -h /tmp store_db -t -c "select tablename from pg_tables where schemaname = 'public'"`; do /usr/local/pgsql/bin/psql -U store_user -h /tmp store_db -c "drop table if exists $i cascade"; done

#for i in `/usr/local/pgsql/bin/psql -U store_user -h /tmp store_db -t -c "select relname from pg_class where relkind='S'"`; do /usr/local/pgsql/bin/psql -U store_user -h /tmp store_db -c "drop sequence $i"; done

mkdir -p ${STORE_STAGE_HOME}
file=${RELEASE_DIR}/store/store-${STORE_STAGE_VERSION}.zip
cd ${STORE_STAGE_HOME}
for r in `find . -name RUNNING_PID`; do
  kill `cat $r`
done
sleep 30
rm -rf store-*
unzip -q ${file}
cd store-${STORE_STAGE_VERSION}
chmod +x store

cnt=0
while [ ! -e RUNNING_PID ]; do
    BUILD_ID=donotKillMe nohup ./store -Dconfig.resource=stage.conf -DapplyEvolutions.default=true -DapplyDownEvolutions.default=true -Djava.net.preferIPv4Stack=true >stdout 2>stderr &

    cnt=$((cnt+1))
    if [ $cnt -gt 10 ]
    then
        echo "Cannot start applicaiont!"
        exit 1
    fi
    
    sleep 30
done
